version: '3'

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    image: sheglar/kittygram_backend
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - be_static:/app/collected_static
      - media:/app/media
  
  frontend:
    image: sheglar/kittygram_frontend
    env_file: .env
    depends_on:
      backend:
        condition: service_started
    volumes:
      - fe_static:/app/build
  
  gateway:
    image: sheglar/kittygram_gateway
    env_file: .env
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started 
    ports:
      - 80:80
    volumes:
      - fe_static:/var/html/static
      - be_static:/var/html/backend
      - media:/var/html/media

volumes:
  pg_data:
  media:
  be_static:
  fe_static:
