name: Main Kittygram Workflow

on:
  push:
    branches:
      - main

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Update pip
      run: |
        python3 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        cd backend && pip install -r requirements.txt --no-cache-dir
    
    - name: Run PEP8 check
      run: |
        cd backend/
        python -m flake8
  
  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      
      - name: Test frontend
        run: |
          cd frontend/
          npm run test
  
  push_to_registry:
    name: Push Docker images to DockerHub
    runs-on: ubuntu-latest
    needs: 
     - backend_tests
     - frontend_tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login DockerHub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_backend:latest

      - name: Build and push frontend image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend:latest 
      
      - name: Build and push gateway image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.production.yml"
          target: "kittygram"
      
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd kittygram

            sudo docker compose -f docker-compose.production.yml pull

            sudo docker compose -f docker-compose.production.yml down
            sudo docker compose -f docker-compose.production.yml up -d

            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
            sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /static/static/
  
  server_tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

  notify:
    runs-on: ubuntu-latest
    needs: 
      - deploy
      - server_tests
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Приложение Kittygram прошло тесты и успешно развернуто!

            Информация о коммите:
            Автор: ${{ github.actor }}
            Сообщение: ${{ github.event.commits[0].message }}
            Репозиторий: ${{ github.repository }}
            
            Детали: https://github.com/${{ github.repository }}/commit/${{github.sha}}
